[package]
name = "galaxy-restore-dump-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = [ "derive" ] }
anyhow = "1.0.95"
tracing = "0.1"
tracing-subscriber = "0.3"
dirs = "6"